{
    not: false,
    isRules: undefined,
    statusCode: undefined,
    name: 'rule',
    isTpl: false,
    root: null,
    wildcard: undefined,
    isRegExp: false,
    isExact: undefined,
    protocol: null,
    pattern: 'www.liangtengfeng.fit/',
    matcher: 'mail.meizu.com',
    port: undefined,
    raw: 'www.liangtengfeng.fit mail.meizu.com',
    isDomain: true,
    rawPattern: 'www.liangtengfeng.fit',
    filters: undefined,
    lineProps: {},
    realPort: undefined
  },
  {
    not: false,
    isRules: undefined,
    statusCode: undefined,
    name: 'rule',
    isTpl: undefined,
    root: null,
    wildcard: undefined,
    isRegExp: false,
    isExact: undefined,
    protocol: 'http:',
    pattern: 'http://www.meizu.com/',
    matcher: 'https://www.sanguosha.com/',
    port: undefined,
    raw: 'http://www.meizu.com/ https://www.sanguosha.com/',
    isDomain: false,
    rawPattern: 'http://www.meizu.com/',
    filters: undefined,
    lineProps: {},
    realPort: undefined
  }

{
    not: false,
    isRules: undefined,
    statusCode: undefined,
    name: 'rule',
    isTpl: false,
    root: null,
    wildcard: undefined,
    isRegExp: false,
    isExact: undefined,
    protocol: 'https:',
    pattern: 'https://detail.meizu.com/item/meizu18.html',
    matcher: 'www.baidu.com',
    port: undefined,
    raw: 'https://detail.meizu.com/item/meizu18.html www.baidu.com',
    isDomain: false,
    rawPattern: 'https://detail.meizu.com/item/meizu18.html',
    filters: undefined,
    lineProps: {},
    realPort: undefined
  }

  {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'mail.meizu.com',
  port: null,
  hostname: 'mail.meizu.com',
  hash: null,
  search: '?replaceCurrent=1&url=https%3a%2f%2fmail.meizu.com%2fowa',
  query: 'replaceCurrent=1&url=https%3a%2f%2fmail.meizu.com%2fowa',
  pathname: '/owa/auth/logon.aspx',
  path: '/owa/auth/logon.aspx?replaceCurrent=1&url=https%3a%2f%2fmail.meizu.com%2fowa',
  href: 'https://mail.meizu.com/owa/auth/logon.aspx?replaceCurrent=1&url=https%3a%2f%2fmail.meizu.com%2fowa'
}

{
    not: false,
    isRules: undefined,
    statusCode: undefined,
    name: 'host',
    isTpl: false,
    root: null,
    wildcard: undefined,
    isRegExp: false,
    isExact: undefined,
    protocol: null,
    pattern: 'www.baidu.com/',
    matcher: 'host://222.243.41.15',
    port: '',
    raw: '222.243.41.15   www.baidu.com',
    isDomain: true,
    rawPattern: 'www.baidu.com',
    filters: undefined,
    lineProps: {}
  }


  url: 'host://127.0.0.1',
    files: null,
    not: false,
    name: 'host',
    isTpl: false,
    root: null,
    isRegExp: true,
    protocol: null,
    pattern: /example\.com/i,
    matcher: 'host://127.0.0.1',
    port: '8080',
    raw: '127.0.0.1:8080 /example\\.com/i',
    isDomain: false,
    rawPattern: '/example\\.com/i',
    lineProps: {}


    {
        not: false,
        isRules: undefined,
        statusCode: undefined,
        name: 'rule',
        isTpl: undefined,
        root: null,
        wildcard: undefined,
        isRegExp: false,
        isExact: undefined,
        protocol: null,
        pattern: 'www.taobao.com/',
        matcher: 'file:///Users/meizu/webProjects/flyme-web/package.json',
        port: undefined,
        raw: 'file:///Users/meizu/webProjects/flyme-web/package.json www.taobao.com',
        isDomain: true,
        rawPattern: 'www.taobao.com',
        filters: undefined,
        lineProps: {},
        realPort: undefined
      },
      {
        not: false,
        isRules: undefined,
        statusCode: undefined,
        name: 'rule',
        isTpl: undefined,
        root: null,
        wildcard: undefined,
        isRegExp: false,
        isExact: undefined,
        protocol: null,
        pattern: 'www.baidu.com/',
        matcher: 'www.meizu.com',
        port: undefined,
        raw: 'www.baidu.com www.meizu.com',
        isDomain: true,
        rawPattern: 'www.baidu.com',
        filters: undefined,
        lineProps: {},
        realPort: undefined
      },